services:
  dev:
    image: ${DEV_ECR_IMAGE}
    container_name: dev
    restart: unless-stopped
    env_file:
      - .env.dev
    expose:
      - "3000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - dev
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
