version: '3.8'

services:
  dev:
    image: ${DEV_ECR_IMAGE:-your_fallback_dev_image}
    container_name: dev
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - app_network

  prod1:
    image: ${PROD_ECR_IMAGE:-your_fallback_prod_image}
    container_name: prod1
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - app_network

  prod2:
    image: ${PROD_ECR_IMAGE:-your_fallback_prod_image}
    container_name: prod2
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - dev
    networks:
      - app_network

networks:
  app_network:
    external: true
